from datetime import date

from django.core.management.base import BaseCommand

from events.models import Event, User


EVENTS = [
    {
        "title": "Music Concert",
        "description": "A great music concert featuring top Kenyan artists.",
        "date": date(2026, 10, 18),
        "location": "KICC, Nairobi",
        "category": "Music",
        "featured": True,
        "ticket_price": 2500,
        "available_tickets": 50,
        "image_url": "https://images.unsplash.com/photo-1501281668745-f7d57925c3b4?auto=format&fit=crop&w=1350&q=80",
    },
    {
        "title": "East Africa Tech Forum",
        "description": "A technology forum exploring AI, blockchain, and cloud computing.",
        "date": date(2026, 11, 7),
        "location": "Sarit Centre, Nairobi",
        "category": "Technology",
        "featured": False,
        "ticket_price": 3000,
        "available_tickets": 50,
        "image_url": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1350&q=80",
    },
    {
        "title": "Food & Wine Festival",
        "description": "Experience the best of Kenyan cuisine and international wines.",
        "date": date(2026, 11, 21),
        "location": "Carnivore Gardens, Nairobi",
        "category": "Food & Drinks",
        "featured": True,
        "ticket_price": 4000,
        "available_tickets": 50,
        "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1350&q=80",
    },
    {
        "title": "Contemporary Africa",
        "description": "A showcase of contemporary African art from emerging artists.",
        "date": date(2026, 12, 5),
        "location": "National Museums of Kenya, Nairobi",
        "category": "Art & Culture",
        "featured": False,
        "ticket_price": 1500,
        "available_tickets": 50,
        "image_url": "https://images.unsplash.com/photo-1580136579312-94651dfd596d?auto=format&fit=crop&w=1350&q=80",
    },
    {
        "title": "Run for Education",
        "description": "An annual charity run supporting education initiatives in Kenya.",
        "date": date(2027, 1, 17),
        "location": "Ngong Road, Nairobi",
        "category": "Sports",
        "featured": True,
        "ticket_price": 2000,
        "available_tickets": 50,
        "image_url": "https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=1350&q=80",
    },
    {
        "title": "East Africa Business Summit",
        "description": "Connecting entrepreneurs and investors across East Africa.",
        "date": date(2027, 2, 12),
        "location": "Radisson Blu, Nairobi",
        "category": "Business",
        "featured": False,
        "ticket_price": 5000,
        "available_tickets": 50,
        "image_url": "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1350&q=80",
    },
]


class Command(BaseCommand):
    help = "Seed Eventify demo data. Passwords are supplied through environment variables or generated by Django."

    def add_arguments(self, parser):
        parser.add_argument("--admin-email", default="admin@example.com")
        parser.add_argument("--admin-password", default=None)
        parser.add_argument("--user-email", default="user@example.com")
        parser.add_argument("--user-password", default=None)

    def handle(self, *args, **options):
        admin_password = options["admin_password"] or "change-me-admin"
        user_password = options["user_password"] or "change-me-user"

        admin, _ = User.objects.update_or_create(
            email=options["admin_email"],
            defaults={"name": "Eventify Admin", "role": User.Role.ADMIN, "is_staff": True, "is_superuser": True},
        )
        admin.set_password(admin_password)
        admin.save()

        user, _ = User.objects.update_or_create(
            email=options["user_email"],
            defaults={"name": "Eventify User", "role": User.Role.USER, "is_staff": False, "is_superuser": False},
        )
        user.set_password(user_password)
        user.save()

        for event_data in EVENTS:
            Event.objects.update_or_create(title=event_data["title"], defaults=event_data)

        self.stdout.write(self.style.SUCCESS(f"Seeded {len(EVENTS)} events and demo accounts."))
        self.stdout.write("Use --admin-password and --user-password to set non-default development credentials.")
